print("Enter the parts of speech to create your own story!")
noun_1 = input("Enter a noun")
verb_1 = input("Enter a verb ending in 'ing'")
adverb_1 = input("Enter an adverb")
emotion_1 = input("Enter an emotion")
noun_2 = input("Enter a noun")
verb_2 = input("Enter a verb")
location_1 = input("Enter a location")
print("One day a "+noun_1+ " was "+verb_1+ " and went to the " +location_1+ ". A " +noun_2+ " came and started to " +verb_2+ " " +adverb_1+ ". " +noun_1+ " became very " +emotion_1)
